### ISSUE TITLE
在armbian上未部署成功

### ISSUE THREAD

**Issue by AoXIUy** [soonxf/Micro-Firewall#2]
![1](https://user-images.githubusercontent.com/78833411/220996687-71e1d643-50fd-4ebc-85ce-1d265291121a.PNG)
![2](https://user-images.githubusercontent.com/78833411/220996707-dd8c7e41-d936-4393-9c1d-ffa00b09f9df.PNG)
![3](https://user-images.githubusercontent.com/78833411/220996917-2b3380e6-a4d2-4124-b51c-1b74c2f787e9.PNG)
![image](https://user-images.githubusercontent.com/78833411/220997101-9acf1027-d69d-4d86-b9d5-c17793e908ff.png)
前端没有启动后端已经成功运行了

**Comment by AoXIUy** [comment]
![image](https://user-images.githubusercontent.com/78833411/220998610-14f629be-fc88-476d-95c4-a384fe77ac0f.png)
![image](https://user-images.githubusercontent.com/78833411/220998679-8b7ab883-72b3-47fd-9984-e0ef69971eec.png)
补图

**Comment by AoXIUy** [comment]
![image](https://user-images.githubusercontent.com/78833411/220998824-0f7ac532-f67a-4533-9228-86893f3ad6e7.png)

**Comment by AoXIUy** [comment]
![image](https://user-images.githubusercontent.com/78833411/220998968-2bc6911f-db86-4086-9845-dfdc5ec5856a.png)

**Comment by soonxf** [comment]
pm2 log 查看下日志

**Comment by soonxf** [comment]
pm2 log 查看下日志

也可以进入 express目录，执行 pm2 start index.js --name=HttpServer --exp-backoff-restart-delay=1000 启动http服务器

**Comment by soonxf** [comment]
先删除 pm2 delete 0

**Comment by soonxf** [comment]
pm2 log 查看下日志

也可以进入 express目录，执行 

pm2 delete HttpServer

pm2 start index.js --name=HttpServer --exp-backoff-restart-delay=1000
 
启动http服务器

**Comment by AoXIUy** [comment]
![image](https://user-images.githubusercontent.com/78833411/221141462-0b9928ca-f8a8-45e4-acd1-6f3532423e2a.png)

**Comment by AoXIUy** [comment]
前端后端都已经启动了，arm架构跟x86还是有区别的感谢大佬

**Comment by soonxf** [comment]
你应当自己新建开机自启动的方式

根目录执行

npm run start

express 目录执行

pm2 start index.js --name=HttpServer --exp-backoff-restart-delay=1000
